//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuyenTap.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Account
    {
        public string Usename { get; set; }
        [AllowHtml]
        public string Password { get; set; }
    }
}
